image: golang:1.8-stretch

before_script:
  - wget https://nodejs.org/dist/v6.11.1/node-v6.11.1-linux-x64.tar.xz
  - tar xf node-v6.11.1-linux-x64.tar.xz
  - cp -a node-v6.11.1-linux-x64/* /usr/local/
  - npm install -g yarn grunt-cli
  - mkdir $GOPATH/src/github.com/grafana
  - ln -s . $GOPATH/src/github.com/grafana/grafana
  - cd $GOPATH/src/github.com/grafana/grafana

build:
  stage: build
  script:
    - go run build.go setup
    - go run build.go build
    - yarn install --pure-lockfile
    - npm run build

